// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { PrismaNeon } from "@prisma/adapter-neon";
import * as dotenv from "dotenv";

dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrate: {
    async adapter() {
      return new PrismaNeon({
        connectionString: process.env.DATABASE_URL!,
      });
    },
  },
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});